CREATE TABLE [dbo].[devinst_device_installs] (
    [id_device_install]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [id_claim]              INT            NULL,
    [id_contract]           INT            NULL,
    [id_contractor]         INT            NULL,
    [contractor]            NVARCHAR (150) NULL,
    [et_number]             NVARCHAR (50)  NULL,
    [contract_number]       NVARCHAR (50)  NULL,
    [plan_date]             DATETIME       NULL,
    [id_device_model]       INT            NULL,
    [id_device]             INT            NULL,
    [device_model]          NVARCHAR (150) NULL,
    [device]                NVARCHAR (150) NULL,
    [id_city]               INT            NULL,
    [city]                  NVARCHAR (150) NULL,
    [address]               NVARCHAR (150) NULL,
    [object_name]           NVARCHAR (150) NULL,
    [contact_name]          NVARCHAR (150) NULL,
    [add_devices]           NVARCHAR (500) NULL,
    [id_manager]            INT            NULL,
    [id_service_admin]      INT            NULL,
    [descr]                 NVARCHAR (MAX) NULL,
    [dattim1]               DATETIME       CONSTRAINT [DF_devinst_device_installs_dattim1] DEFAULT (getdate()) NOT NULL,
    [dattim2]               DATETIME       CONSTRAINT [DF_devinst_device_installs_dattim2] DEFAULT ('3.3.3333') NOT NULL,
    [id_creator]            INT            NULL,
    [enabled]               BIT            CONSTRAINT [DF_devinst_device_installs_enabled] DEFAULT ((1)) NOT NULL,
    [id_devinst_state]      INT            NOT NULL,
    [old_id_device_install] INT            NULL,
    CONSTRAINT [PK_devinst_device_installs] PRIMARY KEY CLUSTERED ([id_device_install] ASC)
);

