CREATE TABLE [dbo].[srvpl_contracts] (
    [id_contract]            INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [number]                 NVARCHAR (150)  NOT NULL,
    [id_service_type]        INT             NULL,
    [id_contract_type]       INT             NULL,
    [id_contractor]          INT             NOT NULL,
    [id_contract_status]     INT             NOT NULL,
    [id_manager]             INT             NULL,
    [price]                  DECIMAL (10, 2) CONSTRAINT [DF_srvpl_contracts_price] DEFAULT ((0)) NULL,
    [date_begin]             DATETIME        NULL,
    [date_end]               DATETIME        NULL,
    [id_creator]             INT             NOT NULL,
    [dattim1]                DATETIME        CONSTRAINT [DF_srvpl_contracts_dattim1] DEFAULT (getdate()) NOT NULL,
    [dattim2]                DATETIME        CONSTRAINT [DF_srvpl_contracts_dattim2] DEFAULT ('3.3.3333') NOT NULL,
    [enabled]                BIT             CONSTRAINT [DF_srvpl_contracts_enabled] DEFAULT ((1)) NOT NULL,
    [old_id_contract]        INT             NULL,
    [id_zip_state]           INT             NULL,
    [note]                   NVARCHAR (150)  NULL,
    [contractor_name]        NVARCHAR (250)  NULL,
    [contractor_inn]         NVARCHAR (20)   NULL,
    [id_contract_prolong]    INT             NULL,
    [id_price_discount]      INT             NULL,
    [period_reduction]       BIT             NULL,
    [add_plan_when_deactive] BIT             CONSTRAINT [DF_srvpl_contracts_add_plan_when_deactive] DEFAULT ((0)) NOT NULL,
    [handling_devices]       INT             NULL,
    CONSTRAINT [PK_srvpl_contracts] PRIMARY KEY CLUSTERED ([id_contract] ASC),
    CONSTRAINT [FK_srvpl_contracts_srvpl_contract_statuses] FOREIGN KEY ([id_contract_status]) REFERENCES [dbo].[srvpl_contract_statuses] ([id_contract_status]),
    CONSTRAINT [FK_srvpl_contracts_srvpl_contract_types] FOREIGN KEY ([id_contract_type]) REFERENCES [dbo].[srvpl_contract_types] ([id_contract_type]),
    CONSTRAINT [FK_srvpl_contracts_srvpl_service_types] FOREIGN KEY ([id_service_type]) REFERENCES [dbo].[srvpl_service_types] ([id_service_type])
);

