CREATE TABLE [dbo].[users] (
    [id_user]       INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [sid]           NVARCHAR (50)  NULL,
    [login]         NVARCHAR (50)  NULL,
    [full_name]     NVARCHAR (150) NULL,
    [display_name]  NVARCHAR (70)  NULL,
    [id_position]   INT            NULL,
    [id_manager]    INT            NULL,
    [id_department] INT            NULL,
    [name]          NVARCHAR (50)  NULL,
    [surname]       NVARCHAR (50)  NULL,
    [patronymic]    NVARCHAR (50)  NULL,
    [position]      NVARCHAR (MAX) NULL,
    [phone]         NVARCHAR (20)  NULL,
    [mobile]        NVARCHAR (20)  NULL,
    [manager]       NVARCHAR (MAX) NULL,
    [mail]          NVARCHAR (50)  NULL,
    [info]          NVARCHAR (MAX) NULL,
    [id_city]       INT            NULL,
    [city]          NVARCHAR (50)  NULL,
    [id_company]    INT            NULL,
    [company]       NVARCHAR (100) NULL,
    [department]    NVARCHAR (150) NULL,
    [join_date]     DATETIME       NULL,
    [birth_date]    DATETIME       NULL,
    [id_state]      INT            NULL,
    [dattim1]       DATETIME       CONSTRAINT [DF_users_dattim1] DEFAULT (getdate()) NOT NULL,
    [dattim2]       DATETIME       CONSTRAINT [DF_users_dattim2] DEFAULT ('3.3.3333') NOT NULL,
    [enabled]       BIT            CONSTRAINT [DF_users_enabled] DEFAULT ((1)) NOT NULL,
    [old_id_user]   INT            NULL,
    CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED ([id_user] ASC),
    CONSTRAINT [FK_users_user_states] FOREIGN KEY ([id_state]) REFERENCES [dbo].[user_states] ([id_state])
);

